name: Build UDSClient msi installer
on:
  push:
    branches: [ master, v4.0 ]
  pull_request:
    branches: [ master, v4.0 ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-win64.txt

    - name: Build Picture to Icon
      run: |
        cd src
        pyside6-rcc -o .\UDSResources_rc.py .\UDSResources.qrc

    - name: Create PyInstaller Spec File
      run: |
        cd src
        pyi-makespec --onefile --hidden-import=win32crypt --hidden-import=certifi UDSClient.py

    - name: Generate PyInstaller build
      run: |
        cd src
        pyinstaller UDSClient.spec

    - name: Add WiX to PATH
      run: |
        $env:Path += ";C:\Program Files (x86)\WiX Toolset v3.14\bin"
        echo "PATH=$env:Path" >> $env:GITHUB_ENV

    - name: Copy WiX definition file
      run: Copy-Item .github/UDSClient.wxs -Destination src/

    - name: Extract version from Python file
      run: |
        $lines = Get-Content src/uds/consts.py
        foreach ($line in $lines) {
          if ($line -match "VERSION:\s*\S+\s*=\s*'([\d\.]+)'") {
            $version = $matches[1]
            echo "VERSION=$version" >> $env:GITHUB_ENV
            break
          }
        }
        if (-not $version) {
          throw "VERSION not found in consts.py"
        }

    - name: Patch .wxs file with version
      run: |
        $v = "${{ env.VERSION }}"
        if ($v -notmatch '\d+\.\d+\.\d+\.\d+') {
          $v += '.0'
        }
        (Get-Content src/UDSClient.wxs) -replace 'Version="\d+\.\d+\.\d+\.\d+"', "Version=`"$v`"" |
          Set-Content src/UDSClient.wxs

    - name: Build MSI Installer
      run: |
        cd src
        candle.exe UDSClient.wxs
        light.exe UDSClient.wixobj -o UDSClient.msi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UDSClient-installers-${{ env.VERSION }}-${{ github.sha }}
        path: src/UDSClient.msi